#!/usr/bin/env bash
# Display "Holberton School" 10t and in 9 show Hi

counter=1
while [ $counter -le 10 ]
do
    echo "Holberton School"
    if [ $counter -eq 9 ]
    then
        echo "Hi"
    fi
    ((counter++))
done
