#!/usr/bin/env bash
# Displays the time 

counter=0
while [ $counter -le 12 ]
do
    echo "Hour: $counter"
    min=1
    while [ $min -lt 60 ]
    do
        echo "$min"
        ((min++))
    done
    ((counter++))
done
